Myaso/Models/FAQ.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Myaso.Models
{
    public class Faq
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<FaqDescription> FaqDescriptions { get; set; }

    }
}

Myaso/ViewModels/FaqViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Myaso.Models;

namespace Myaso.ViewModels
{
    public class FaqViewModel
    {
        public Faq Faq { get; set; }
        public IQueryable<FaqDescription> FaqDescriptions { get; set; } 
    }
}

Myaso/Controllers/FaqController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Myaso.Models;
using Newtonsoft.Json;

namespace Myaso.Controllers
{
    public class FaqController : Controller
    {
        private ApplictionDbContext Context;

        public FaqController(ApplictionDbContext applictionDbContext)
        {
            Context = applictionDbContext;
        }

        // GET: Faq
        public ActionResult Index()
        {
            IQueryable<Faq> faqs = Context.Faqs.Include(f => f.FaqDescriptions);
            return View(faqs);
        }

        // GET: Faq/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Faq/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Faq/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Faq faq)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Context.Faqs.Add(faq);
                    Context.SaveChanges();
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Faq/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Faq/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Faq faq)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Context.Faqs.Update(faq);
                    Context.SaveChanges();
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Faq/Delete/5
        public ActionResult Delete(int id)
        {
            Faq f = Context.Faqs.First(d => d.Id == id);
            return View(f);
        }

        // POST: Faq/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteItem(int id)
        {
            try
            {
                Faq f = Context.Faqs.First(d => d.Id == id);
                Context.Entry(f).State = EntityState.Deleted;
                Context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public string Test(string faqName = "Продукты")
        {
            Faq model = Context.Faqs.Include(f => f.FaqDescriptions).FirstOrDefault(f => f.Name.Contains(faqName));
            string s = JsonConvert.SerializeObject(model,
                new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
            return JsonConvert.SerializeObject(model,
                new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
        }
    }
}

Myaso/Views/Shared/_AdminPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/vendor.min.css" />
        <link rel="stylesheet" type="text/css" href="styles/font-awesome.min.css">
    </environment>
</head>
<body>
    @{
        Html.RenderPartial("_NavigationMenu");
    }
    <div class="row flex-xl-nowrap">
        <div class="col-12 col-md-3 col-xl-2 bd-sidebar">
            <div class="list-group">
                <a class="list-group-item list-group-item-action" asp-action="Index" asp-controller="Plan" asp-route-sortOrder="@ViewBag.UserSort"><b>Планы</b></a>
                <a class="list-group-item list-group-item-action" asp-action="Index" asp-controller="Dish" asp-route-sortOrder="@ViewBag.UserSort"><b>Блюда</b></a>
                <a class="list-group-item list-group-item-action" asp-action="Index" asp-controller="Menu" asp-route-sortOrder="@ViewBag.UserSort"><b>Заполнение меню</b></a>
                <a class="list-group-item list-group-item-action" asp-action="Index" asp-controller="Faq" asp-route-sortOrder="@ViewBag.UserSort"><b>Заполнение FAQ</b></a>
            </div>
            @*<ul class="nav nav-pills flex-column">
                <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="Plan" asp-route-sortOrder="@ViewBag.UserSort"><b>Планы</b></a> </li>
                <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="Dish" asp-route-sortOrder="@ViewBag.UserSort"><b>Блюда</b></a> </li>
                <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="Menu" asp-route-sortOrder="@ViewBag.UserSort"><b>Заполнение меню</b></a> </li>
                <li class="nav-item"><a class="nav-link" asp-action="Edit" asp-controller="Menu" asp-route-sortOrder="@ViewBag.UserSort"><b>Заполнение меню_test</b></a> </li>
                <li class="nav-item"><a class="nav-link" asp-action="Admin" asp-controller="User" asp-route-sortOrder="@ViewBag.UserSort"><b>Изменить блюда</b></a> </li>
            </ul>*@
        </div>
        @*<nav class="collapse bd-links" id="bd-docs-nav">
            <div class="bd-toc-item >
                <ul class="nav bd-sidenav">
                    <li class="active bd-sidenav-active"><a class="nav-link" asp-action="Index" asp-controller="Plan" asp-route-sortOrder="@ViewBag.UserSort"><b>Планы</b></a> </li>
                    <li class="active bd-sidenav-active"><a class="nav-link" asp-action="Index" asp-controller="Dish" asp-route-sortOrder="@ViewBag.UserSort"><b>Блюда</b></a> </li>
                    <li class="active bd-sidenav-active"><a class="nav-link" asp-action="Index" asp-controller="Menu" asp-route-sortOrder="@ViewBag.UserSort"><b>Заполнение меню</b></a> </li>
                    <li class="active bd-sidenav-active"><a class="nav-link" asp-action="Edit" asp-controller="Menu" asp-route-sortOrder="@ViewBag.UserSort"><b>Заполнение меню_test</b></a> </li>
                    <li class="active bd-sidenav-active"><a class="nav-link" asp-action="Admin" asp-route-sortOrder="@ViewBag.UserSort"><b>Изменить блюда</b></a> </li>
                </ul>
                
            </div>            
        </nav>*@
        <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 bd-content" role="main">
            @RenderBody()
        </main>
        <div class="container">

        </div>
    </div>
    
    <div>

    </div>
    <div class="admin-menu-list">

    </div>
    <div>

    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/vendor.min.js"></script>
    </environment>
</body>
</html>

Myaso/Views/Shared/_FAQ.cshtml
@model Myaso.ViewModels.PlanViewModel

    
    @foreach (var desc in Model.FaqDescriptions)
    {
        <div id="faqname">@desc.Name</div>
        <div id="faqdescription">@desc.Description</div>
    }
    

Myaso/Views/Shared/_GetDaysWeeks.cshtml
<div class="day-week-container">
    <div class="row" id="dayweek-selectors-container">
        <div class="row col-md-8" id="day-selector">
            <nav class="nav nav-tabs" id="daysTab" role="tablist">
                @foreach (var day in Model.Days)
                {
                    <span class="col-md-1 nav-item nav-link day-selection" id="day-items" data-toggle="tab" role="tab" onclick="selectDayMenu('@day.NameEn')" style="cursor: pointer">@day.Name</span>
                }
            </nav>
        </div>
        <div class=" row col-md-4" id="week-selector">
            <nav class="nav nav-tabs" id="weeksTab" role="tablist">
                @foreach (var week in Model.Weeks)
                {
                    <span class="col-md-6 nav-item nav-link week" id="week-items" data-toggle="tab" role="tab" onclick="selectweek('@week.Id')" style="cursor: pointer">@week.Name</span>
                }
            </nav>
        </div>
    </div>
</div>

Myaso/Views/Shared/_GetDishes.cshtml
@model Myaso.ViewModels.PlanViewModel

<div class="row" id="menu-items">
    @foreach (var item in Model.DishToPlans)
    {
        <div class="col-md-6 col-lg-4 text-white">
            <img class="card-img" id="dish-Image-@item.Food.Id" src="@item.Dish.DishImagePath" alt="Card image">
            <div class="card-img-overlay" id="dishes-hover">
                <h6 class="card-title">@item.Food.Name</h6>
                <p class="card-text dishName" id="dish-Name-@item.Food.Id">@item.Dish.Name</p>
                <div class="card-text" id="dish-weight-@item.Food.Id">@item.Dish.WeigthAndCalories</div>
                <div class="card-text proteins" id="dish-proteins-@item.Food.Id">@item.Dish.Proteins</div>
            </div>
        </div>
    }
    @*Сюда можно будет добавить карту с общим колиеством кал*@
</div>
@section Scripts{
    <script>
        
    </script>
}


@*вешаем на место карточки псевдоэлемент и текст всплывающий это css анимация*@




@*<div class="row dishes" id="menu-items">
        @foreach (var item in Model.DishToPlans)
        {
            <div class="col-md-6 col-lg-4 cardtest">
                <img class="img" id="dish-Image-@item.Food.Id" src="@item.Dish.DishImagePath" alt="Card image">
                <div class="img-overlay">
                    <h6 class="card-title">@item.Food.Name</h6>
                    <div class="card-text" id="dish-Name-@item.Food.Id">@item.Dish.Name</div>
                    <div class="card-text" id="dish-weight-@item.Food.Id">@item.Dish.WeigthAndCalories</div>
                    <div class="card-text" id="dish-proteins-@item.Food.Id">@item.Dish.Proteins</div>
                </div>
            </div>
        }
        @*Сюда можно будет добавить карту с общим колиеством кал*
    </div>*@


@*<div id="dishes-row" data-js="dfd">
        <div class="col" id="dish-Name-@item.Food.Id">
            @item.Dish.Name
        </div>
        <div class="col" id="food-Name-@item.Food.Id">
            @item.Food.Name
        </div>
        <div class="col" id="dish-weight-@item.Food.Id">
            @item.Dish.WeigthAndCalories
        </div>
        <div class="col" id="dish-proteins-@item.Food.Id">
            @item.Dish.Proteins
        </div>
        <div class="col" id="plan-Name-@item.Food.Id">
            @item.PlanToDay.Plan.Name
        </div>
        <div class="col" id="dish-Image-@item.Food.Id">
            <img src="@item.Dish.DishImagePath"/>
        </div>
    </div>*@

Myaso/Views/Shared/_GetMainPage.cshtml
@model Myaso.ViewModels.PlanViewModel

@{
    ViewData["Title"] = "Index";
}
@{
    Html.RenderPartial("_GetPlans");@*Сюда подгружается список планов*@
}
<hr />
<div class=" row container-plan-description">
    <h3 id="planshortDescription">@Model.Plan.ShortDescription</h3>
    <div class="row col-md-8" id="plandescription">@Model.Plan.Description</div>
</div>
@*<div id="test-plan"></div>*@
<div id="settings" data-plan="@Model.Plan.Name" data-day="@Model.Day.NameEn" data-week="@Model.Week.Id"></div>
@*<div id="jsTesting" data-js="dfd"></div>*@

@{
    Html.RenderPartial("_GetDaysWeeks");@*Сюда подгружается список дней и недель*@
}

@*<div class="day-week-container">
    <div class="row" id="dayweek-selectors-container">
        <div class="row col-md-8" id="day-selector">
            <nav class="nav nav-tabs" id="daysTab" role="tablist">
                @foreach (var day in Model.Days)
                {
                    <span class="col-md-1 nav-item nav-link day-selection" id="day-items" data-toggle="tab" role="tab" onclick="selectDayMenu('@day.NameEn')" style="cursor: pointer">@day.Name</span>
                }
            </nav>
        </div>
        <div class=" row col-md-4" id="week-selector">
            <nav class="nav nav-tabs" id="weeksTab" role="tablist">
                @foreach (var week in Model.Weeks)
                {
                    <span class="col-md-6 nav-item nav-link week" id="week-items" data-toggle="tab" role="tab" onclick="selectweek('@week.Id')" style="cursor: pointer">@week.Name</span>
                }
            </nav>
        </div>
    </div>
</div>*@
<div class="row" id="menu-container">
    <div class="row col-md-8" id="loadDishes"></div>@*Сюда подгружается список блюд*@
    <div class="row col-md-4" id="menu-items-description">
        @*Здесь отображается описание плана*@
        @if (User.Identity.IsAuthenticated)
        {
            <div id="menu-description-form">
                <input type="hidden" id="days5" value="5 будних" />
                <input type="hidden" id="days7" value="7 дней" />
                <div>
                    <form asp-action="OrderDetails" asp-controller="Order" name="form" asp-antiforgery="true">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <input type="hidden" name="description" class="form-control" value="@Model.OrderDesc.Description" />
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="planPrice" class="form-control" value="@Model.OrderDesc.PlanPrice" />
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="planName" class="form-control" value="@Model.Plan.Name" />
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="userId" class="form-control" value="@Model.User.Phone" />
                        </div>
                        <div class="form-group">
                            <h3 id="planName" class="control-label">@Model.Plan.Name</h3>
                            <h5 id="caloriesQuantity">≈ @Model.Plan.CaloriesQuantity</h5>
                            <nav class="nav nav-tabs flex-column" id="dayqtyTab" role="tablist">
                                <span class="nav-item nav-link" data-toggle="tab" role="tab" id="select-days5" onclick="selectdays(document.getElementById('days5').value)" style="cursor: pointer">
                                    На 5 дней
                                </span>
                                <span class="nav-item nav-link" data-toggle="tab" role="tab" id="select-days7" onclick="selectdays(document.getElementById('days7').value)" style="cursor: pointer">
                                    На 7 дней
                                </span>
                            </nav>
                            <div id="orderDescription" class="control-label">@Model.OrderDesc.Description</div>
                            <div id="planPrice" class="control-label">@Model.OrderDesc.PlanPrice</div>
                            <div id="pricePerDay" class="control-label">≈ @Model.OrderDesc.PricePerDay в день</div>
                            <div id="pricePerDish" class="control-label">≈ @Model.OrderDesc.PricePerDish за блюдо</div>
                            <input type="submit" value="Заказать" class="btn btn-default" />
                            <div id="timeOfDelivery" class="control-label">@Model.OrderDesc.TimeOfDelivery</div>
                        </div>
                    </form>
                </div>
            </div>
        }
        else
        {
            <div id="menu-description-form">
                <input type="hidden" id="days5" value="5 будних" />
                <input type="hidden" id="days7" value="7 дней" />
                <div>
                    <form asp-action="Register" asp-controller="Account" name="form">
                        <div class="form-inline form-group">
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="description" class="form-control" value="Not Used" />
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="planPrice" class="form-control" value="Not Used" />
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="planName" class="form-control" value="" />
                        </div>
                        <div class="form-group">
                            <h3 id="planName" class="control-label">@Model.Plan.Name</h3>
                            <h5 id="caloriesQuantity">≈ @Model.Plan.CaloriesQuantity</h5>
                            <nav class="nav nav-tabs flex-column" id="dayqtyTab" role="tablist">
                                <span class="nav-item nav-link" data-toggle="tab" role="tab" id="select-days5" onclick="selectdays(document.getElementById('days5').value)" style="cursor: pointer">
                                    На 5 дней
                                </span>
                                <span class="nav-item nav-link" data-toggle="tab" role="tab" id="select-days7" onclick="selectdays(document.getElementById('days7').value)" style="cursor: pointer">
                                    На 7 дней
                                </span>
                            </nav>
                            <div id="orderDescription" class="control-label">@Model.OrderDesc.Description</div>
                            <div id="planPrice" class="control-label">@Model.OrderDesc.PlanPrice</div>
                            <div id="pricePerDay" class="control-label">≈ @Model.OrderDesc.PricePerDay в день</div>
                            <div id="pricePerDish" class="control-label">≈ @Model.OrderDesc.PricePerDish за блюдо</div>
                            <input type="submit" value="Заказать" class="btn btn-default" />
                            <div id="timeOfDelivery" class="control-label">@Model.OrderDesc.TimeOfDelivery</div>
                        </div>
                    </form>
                </div>
            </div>
        }
    </div>
    <hr />
</div>

Myaso/Views/Shared/_GetPlans.cshtml
@model Myaso.ViewModels.PlanViewModel

<div class="week-ration">
    <h1>Выберите рацион для своей недели</h1>
    <hr />
</div>

<nav class="nav nav-pills" id="myTab" role="tablist">
    @foreach (var plan in Model.Plans)
    {
        <div class="menu-items nav-item nav-link" data-toggle="tab" role="tab" id="plan-items-@plan.Name" onclick="selectplan('@plan.Name')" style="cursor: pointer">
            <h3 id="plan-name">@plan.Name</h3>
            <div id="plan-calories">≈ @plan.CaloriesQuantity</div>
        </div>
    }
</nav>

Myaso/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Myaso</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/vendor.min.css" />
        <link rel="stylesheet" type="text/css" href="styles/font-awesome.min.css">
    </environment>
</head>
<body>
@{
    Html.RenderPartial("_NavigationMenu");
}
@*<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Myaso</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @if (!User.Identity.IsAuthenticated)
                {
                    <li><a asp-area="" asp-controller="Account" asp-action="Login">Вход</a></li>
                    <li><a asp-area="" asp-controller="Account" asp-action="Register">Регистрация</a></li>
                    <li><a asp-action="Edit" asp-controller="Menu" asp-route-sortOrder="@ViewBag.UserSort"><b>Заполнение меню_test</b></a> </li>

                }
                else
                {
                            <li><a asp-area="" asp-controller="User" asp-action="UserProfile">@User.Identity.Name</a></li>
                    <li><a asp-area="" asp-controller="User" asp-action="UserProfile">Профиль @User.Identity.Name</a></li>
                    <li><a asp-area="" asp-controller="User" asp-action="Admin">Управление</a></li>
                            <li><a asp-area="" asp-controller="User" asp-action="Moderator">Модер</a></li>
                    <li><a asp-area="" asp-controller="Account" asp-action="Logout">Выйти</a></li>
                }
            </ul>
        </div>
    </div>
</nav>*@
@*<div id="imagebanner"><img class="" src="/images/Header1.jpg" alt="banner"></div>*@
<div id="promo">
    <div id="banner-inner" style="color: rgb(255, 255, 255);">

        <h1 id="yagla-192003">Доставим готовую<br>еду на всю неделю</h1>
        <div id="price-line">от <span class="">690</span> <span class=""></span> в день</div>
        <div id="actions">
            <a href="#menu-plans" data-tid="top-button" id="green button">Выбрать рацион</a>
            <div id="recall-button"><a href="#" id="button green outline">Перезвонить мне</a> <!----></div>
        </div>
    </div>
</div>
<div class="container">

</div>
<div class="main-menu-choise">
    <div class="container body-content">
        @RenderBody()
        <hr/>
    </div>
</div>
<div class="FAQ">
    <div class="container">
        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">Contact</a>
            </li>
        </ul>
        <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                Consequat occaecat ullamco amet non eiusmod nostrud dolore irure incididunt est duis anim sunt officia. Fugiat velit proident aliquip nisi incididunt nostrud exercitation proident est nisi. Irure magna elit commodo anim ex veniam culpa eiusmod id nostrud sit cupidatat in veniam ad. Eiusmod consequat eu adipisicing minim anim aliquip cupidatat culpa excepteur quis. Occaecat sit eu exercitation irure Lorem incididunt nostrud.
            </div>
            <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                Ad pariatur nostrud pariatur exercitation ipsum ipsum culpa mollit commodo mollit ex. Aute sunt incididunt amet commodo est sint nisi deserunt pariatur do. Aliquip ex eiusmod voluptate exercitation cillum id incididunt elit sunt. Qui minim sit magna Lorem id et dolore velit Lorem amet exercitation duis deserunt. Anim id labore elit adipisicing ut in id occaecat pariatur ut ullamco ea tempor duis.
            </div>
            <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
                Est quis nulla laborum officia ad nisi ex nostrud culpa Lorem excepteur aliquip dolor aliqua irure ex. Nulla ut duis ipsum nisi elit fugiat commodo sunt reprehenderit laborum veniam eu veniam. Eiusmod minim exercitation fugiat irure ex labore incididunt do fugiat commodo aliquip sit id deserunt reprehenderit aliquip nostrud. Amet ex cupidatat excepteur aute veniam incididunt mollit cupidatat esse irure officia elit do ipsum ullamco Lorem. Ullamco ut ad minim do mollit labore ipsum laboris ipsum commodo sunt tempor enim incididunt. Commodo quis sunt dolore aliquip aute tempor irure magna enim minim reprehenderit. Ullamco consectetur culpa veniam sint cillum aliqua incididunt velit ullamco sunt ullamco quis quis commodo voluptate. Mollit nulla nostrud adipisicing aliqua cupidatat aliqua pariatur mollit voluptate voluptate consequat non.
            </div>
        </div>
    </div>
</div>
<div class="footer">
    <div class="container footer-content">
        <footer>
            <p>&copy; 2018 - Myaso</p>
        </footer>
    </div>
</div>


<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="~/vendor.min.js"></script>
</environment>

@RenderSection("Scripts", required: false)
</body>
</html>